version: "3.7"

services:

  # Accessible at http://localhost:3000
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.back
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Accessible at http://localhost:3001
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.front
    ports:
      - "3001:8000"
    depends_on:
      - db
      - backend
    environment:
      # Provide only if the backend URI is different to the frontend URI
      - BACKEND_URI=http://localhost:3000
    volumes:
      - ./src/front:/front

  # Database accessible at postgres://USER:PASSWORD@localhost/postgres
  db:
    image: postgres
    env_file: .env
    ports:
     - "5432:5432"
